drop nompi variant of libnetcdf; remove unused code in recipe/build.sh
conda-forge/libcf-feedstock pull request #38
Opened 2020-05-06 22:57 UTC by muryanto1

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-05-06 22:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipe**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

2020-05-06 22:58 UTC, muryanto1 commented
@conda-forge-admin, please rerender

2020-06-01 18:39 UTC, xylar requested changes
I don't think the nompi variant should be dropped.  I think as long as the library doesn't depend on MPI, the nompi variant is the right one to build with.

2020-06-01 19:21 UTC, muryanto1 commented
@xylar agree. I have run tests for all cdat packages with test envs with nompi, mpich and openmpi libnetcdf variants. We ran into problem with vcs (with vtk-cdat) on linux with mpich, 
I am closing this PR.

2020-06-01 19:21 UTC, closed without merging